### PR TITLE
Update 1-investing-options.list

### PR DESCRIPTION
**Pull request by Chaitra-HR**

### CODE REVIEW

**Comment by Chaitra-HR** [comment]
added all investment vehicles

**Comment by nahushi** [comment]
Well done. In the next part to this, we need a detailed classification to get common functionalities to avoid duplication of work.

**Comment by nahushi** [comment]
Hi Chaitra,

Can you please update me on the progress of requirement gathering? I am
waiting for next steps for API understanding, sooner we finish, better we
can land the pitch safely.

Thanks,
nahusha

**Comment by Chaitra-HR** [comment]
Sure, will be done by 12 am

**Pull request merged**
